# -*- coding: utf-8 -*-
"""Copy of web_scraping_jettyAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TtBYmuVzqrH3KztR_Y3DBnmhSelLTjCN
"""

!pip install BeautifulSoup

!pip install lxml

import requests #download webpage
html_text = requests.get(url='https://www.coursera.org/search?query=artificial%20intelligence').text #url
print(html_text)

soup = BeautifulSoup( html_text, 'lxml')
#grab all header tags
course_title = soup.find_all('h3',class_ = 'cds-CommonCard-title css-6ecy9b')
for courses in course_title:
  print(courses.text)
Skills = soup.find_all('div', class_ = 'cds-ProductCard-body')
for skill in Skills:
  print(skill.text)
Duration = soup.find_all('div',class_ ='cds-CommonCard-metadata')
for duration in Duration:
  print(duration.text)

data = {
"source_url": "url",
"source_type": "blog",
"author": "",
"published_date": "",
"language": "",
"region": "",
"topic_tags": [],
"trust_score": "",
"content_chunks":
}

!pip install youtube-transcript-api yt-dlp

video_url = input("YouTube URL: https://youtu.be/LPZh9BOjkQs?si=1E5TerfMu-ekNJug")

import json
import re
from yt_dlp import YoutubeDL
from youtube_transcript_api import YouTubeTranscriptApi


def extract_video_id(url):
    pattern = r"(?:v=|\/)([0-9A-Za-z_-]{11}).*"
    match = re.search(pattern, url)

    if match:
        return match.group(1)

    return None


def scrape_youtube(video_url):

    ydl_opts = {
        "quiet": True
    }

    # Metadata
    with YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(video_url, download=False)

    title = info.get("title")
    channel = info.get("uploader")
    publish_date = info.get("upload_date")
    description = info.get("description")

    # Transcript
    video_id = extract_video_id(video_url)

    transcript_text = ""

    try:
        transcript = YouTubeTranscriptApi.get_transcript(video_id)

        transcript_text = " ".join(
            [item["text"] for item in transcript]
        )

    except Exception:
        transcript_text = "Transcript unavailable"

    # Content chunks
    chunks = []

    chunk_size = 500

    for i in range(0, len(transcript_text), chunk_size):
        chunks.append(
            transcript_text[i:i+chunk_size]
        )

    data = {
        "source_url": video_url,
        "source_type": "youtube",
        "Channel_name": channel,
        "Video_publish_date": publish_date,
        "language": "unknown",
        "region": "unknown",
        "topic_tags": [],
        "trust_score": 0.7,
        "content_chunks": chunks,
        "title": title,
        "video_description": description
    }

    return data

video_url = input("Enter YouTube URL: ")

result = scrape_youtube(video_url)

print(json.dumps(result, indent=4))

!pip install biopython

from Bio import Entrez
import json
Entrez.email = "pinochhioshree@gmail|.com"

from Bio import Entrez
import json

Entrez.email = "your_email@example.com"


def scrape_pubmed(pubmed_id):

    handle = Entrez.efetch(
        db="pubmed",
        id=pubmed_id,
        rettype="abstract",
        retmode="xml"
    )

    records = Entrez.read(handle)

    article = records["PubmedArticle"][0]

    article_data = article["MedlineCitation"]["Article"]

    # Title
    title = str(article_data.get("ArticleTitle", ""))

    # Authors
    authors = []

    if "AuthorList" in article_data:

        for author in article_data["AuthorList"]:

            lastname = author.get("LastName", "")
            firstname = author.get("ForeName", "")

            authors.append(
                f"{firstname} {lastname}".strip()
            )

    # Abstract
    abstract = ""

    if "Abstract" in article_data:

        abstract_parts = article_data["Abstract"]["AbstractText"]

        abstract = " ".join(
            map(str, abstract_parts)
        )

    # Journal

    journal = article_data["Journal"]["Title"]

    # Publication Year

    year = ""

    try:

        year = article_data["Journal"]["JournalIssue"][
            "PubDate"
        ]["Year"]

    except:

        year = "Unknown"

    data = {
        "source_url": f"https://pubmed.ncbi.nlm.nih.gov/{pubmed_id}/",
        "source_type": "pubmed",
        "author": authors,
        "published_date": year,
        "language": "English",
        "region": "Unknown",
        "topic_tags": [],
        "trust_score": 0.9,
        "content_chunks": [abstract],
        "title": title,
        "journal": journal
    }

    return data

pubmed_id = input("Enter PubMed ID: ")

result = scrape_pubmed(pubmed_id)

print(json.dumps(result, indent=4))

from datetime import datetime


def get_author_score(author):

    if author and str(author).strip():
        return 0.8

    return 0.3


def get_domain_score(url):

    url = url.lower()

    if "pubmed" in url:
        return 1.0

    elif "youtube" in url or "youtu.be" in url:
        return 0.7

    elif ".edu" in url:
        return 0.9

    elif ".gov" in url:
        return 0.95

    elif ".org" in url:
        return 0.8

    elif ".com" in url:
        return 0.6

    return 0.4


def get_citation_score(citation_count):

    if citation_count >= 20:
        return 1.0

    elif citation_count >= 10:
        return 0.8

    elif citation_count >= 5:
        return 0.6

    elif citation_count > 0:
        return 0.4

    return 0.2


def get_recency_score(year):

    try:

        current_year = datetime.now().year

        age = current_year - int(year)

        if age <= 1:
            return 1.0

        elif age <= 3:
            return 0.8

        elif age <= 5:
            return 0.6

        else:
            return 0.3

    except:
        return 0.5


def get_disclaimer_score(text):

    text = text.lower()

    keywords = [
        "educational purposes",
        "consult a doctor",
        "medical advice",
        "healthcare professional"
    ]

    for keyword in keywords:

        if keyword in text:
            return 1.0

    return 0.0


def calculate_trust_score(
    source_url,
    author,
    published_year,
    citation_count,
    content_text
):

    author_score = get_author_score(author)

    domain_score = get_domain_score(source_url)

    citation_score = get_citation_score(citation_count)

    recency_score = get_recency_score(published_year)

    disclaimer_score = get_disclaimer_score(content_text)

    trust_score = (
        0.25 * author_score +
        0.25 * domain_score +
        0.20 * citation_score +
        0.20 * recency_score +
        0.10 * disclaimer_score
    )

    return round(trust_score, 2)

youtube_score = calculate_trust_score(
    source_url="https://youtu.be/LPZh9BOjkQs?si=OOq9x-Jdpv-HGUEs",
    author="3Blue1Brown",
    published_year="2024",
    citation_count=0,
    content_text="Educational purposes only."
)

print("YouTube Score:", youtube_score)

pubmed_score = calculate_trust_score(
    source_url="https://pubmed.ncbi.nlm.nih.gov/29860986/",
    author="Research Team",
    published_year="2024",
    citation_count=35,
    content_text="This study investigates machine learning methods."
)

print("PubMed Score:", pubmed_score)

blog_score = calculate_trust_score(
    source_url="https://towardsdatascience.com/sample-article",
    author="John Doe",
    published_year="2025",
    citation_count=5,
    content_text="This article explains AI and ML concepts."
)

print("Blog Score:", blog_score)

import os

print(os.getcwd())

